### PR TITLE
fix: evil-state error

### LINKED ISSUE #461: Conflicts with `which-key`
**Describe the bug**
`which-key` [defines](https://github.com/justbur/emacs-which-key/blob/521a59b6f461232a008fba62f79bbb14f487b16e/which-key.el#L717) a var `evil-state` and [this line](https://github.com/bdarcus/citar/blob/main/citar-org.el#L296) causes an void function error when `evil` is not installed.

```
Debugger entered--Lisp error: (void-function evil-insert)
  (evil-insert 1)
  (progn (evil-insert 1))
  eval((progn (evil-insert 1)) t)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x425ae573>)(nil)
  #f(compiled-function (&rest _it) #<bytecode 0x1ff54a136c25>)()
  eval-sexp-fu-flash-doit-simple(#f(compiled-function (&rest _it) #<bytecode 0x1ff54a136c25>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf19>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf39>))
  eval-sexp-fu-flash-doit(#f(compiled-function (&rest _it) #<bytecode 0x1ff54a136c25>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf19>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf39>))
  esf-flash-doit(#f(compiled-function (&rest _it) #<bytecode 0x1ff54a136c25>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf19>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf39>) #f(compiled-function (&rest args2) #<bytecode 0x1ff52345cf59>))
  ad-Advice-eval-last-sexp(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x425ae573>) nil)
  apply(ad-Advice-eval-last-sexp #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x425ae573>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Emacs version:**
`GNU Emacs 27.2 (build 1, x86_64-apple-darwin21.1.0, Carbon Version 165 AppKit 2113) of 2021-11-18`

### PR DESCRIPTION
**Pull request by bdarcus**
Can you check if this fixes it @Yevgnen?

------

Fix #461.

### CODE REVIEW

**Comment by Yevgnen** [comment]
Unfortunately , it didn't. I think the `boundp` check is `t` and thus the `evil-insert` call but it's not found when `evil` is not installed.

**Comment by Yevgnen** [comment]
Still no luck. But when I eval `(when (boundp 'evil-version (evil-insert 1))` using `M-:`, I get `nil`.

**Comment by bdarcus** [comment]
Screenshot doesn't show.

Could you figure it out and submit a PR, or suggest the fix here?

**Comment by Yevgnen** [comment]
I might try that later, I'm gonna get some sleep now :)

**Comment by bdarcus** [comment]
I just changed it to this, which is more direct:

```elisp
      (when (fboundp 'evil-insert)
        (evil-insert 1))))
```

**Pull request merged**
