### PR TITLE
fix(file): dedup default file parser results

### LINKED ISSUE #402: citar-open-library-files returns a list with duplicate files
With `citar-file-open-prompt`set to 't', citar-open-library-files opens a completing-read prompt with duplicate files.

Oddly, the number of duplicates is a factor of the number of directories set in `citar-library-paths`: when set to nil or a single directory, each file is duplicated once (2 files listed); when set to two directories, each file is duplicated twice (4 files listed); three directories, 6 files listed.

I think I've narrowed it down to some of the iterating done in `citar-file-parser-default`. But that's as far as I've gotten. 

A sample bibtex entry:
```
@article{Wilson2004,
  title = {Foucault on the "{{Question}} of the {{Author}}": A {{Critical Exegesis}}},
  shorttitle = {Foucault on the "{{Question}} of the {{Author}}"},
  author = {Wilson, Adrian},
  year = {2004},
  month = apr,
  journal = {The Modern Language Review},
  volume = {99},
  number = {2},
  pages = {339},
  issn = {00267937},
  doi = {10.2307/3738750},
  langid = {english},
  file = {/Users/localauthor/Zotero/storage/LZULTBNK/Wilson2004 - Foucault on the Question of the Author A Critic.pdf}
}
```

### PR DESCRIPTION
**Pull request by localauthor**
Fix #402

fixup! fix(file): dedup default file parser results

### CODE REVIEW

**Comment by bdarcus** [comment]
I guess that's what I get what I don't test a commit! Thanks.

**Comment by bdarcus** [comment]
Though, shouldn't `delete-duplicates` go inside the `when`?

**Comment by localauthor** [comment]
Right, I don't see why not, as a sort of catch-all.

**Comment by bdarcus** [comment]
> Right, I don't see why not, as a sort of catch-all.

It's just more logically correct. 

Done.

**Pull request merged**
