### PR TITLE
fix: citar-citeproc-format-reference, for local-bibs

### LINKED ISSUE #588: citar-citeproc: doesn't work with local bib sources
If I run `citar-copy-reference` with items in a local bib file, citeproc can't find them.

I discovered this when testing #587.

Looking at the code, here's the problem:

https://github.com/bdarcus/citar/blob/a80eaf22a1e789edcd953df09624f34cee337001/citar-citeproc.el#L113

It should be fixed on #589.

cc @localauthor

### PR DESCRIPTION
**Pull request by localauthor**
Fix #588

### CODE REVIEW

**Comment by localauthor** [comment]
Ah! Just saw the other pull request 😆

**Comment by bdarcus** [comment]
I'll merge your's. Thanks!

**Comment by localauthor** [comment]
six of one :)

👍

**Comment by bdarcus** [comment]
Was trivial code, of course, but you're was marginally better :-)

**Pull request merged**
